export const CHECKOUT_ACTION_TYPES = {
    FETCH_CHECKOUT_START : 'checkout/FETCH_CHECKOUT_START',
    POST_CHECKOUT_SUCCESS : 'checkout/POST_CHECKOUT_SUCCESS',
    FETCH_CHECKOUT_ERROR : 'checkout/FETCH_CHECKOUT_ERROR',
    FETCH_CHECKOUT_ADDRESS : 'checkout/FETCH_CHECKOUT_ADDRESS',
    FETCH_RECENT_ITEMS : 'checkout/FETCH_RECENT_ITEMS',
}