export const CART_ACTION_TYPES = {
    SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
    FETCH_CART_ITEMS_START:'cart/SET_CART_ITEMS',
    FETCH_CART_ITEMS_SUCCESS: 'cart/SET_CART_ITEMS_SUCCESS',
    FETCH_CART_ITEMS_ERROR: 'cart/SET_CART_ITEMS_ERROR',
};